$('.owl-carousel').owlCarousel({
    loop:false,
    margin:11,
    nav:false,
    responsive:{
        0:{
            items:1
        },
        420:{
            items:2
        },
        600:{
            items:3
        },
        800:{
            items:4
        },
        1100:{
            items:5
        }
    }
})